import type { Request, Response, NextFunction } from "express";
import { supabase } from "../config/supabase.js";
export interface AuthenticatedUser { id:string; email:string; username:string; role:string; status:string; }
declare global { namespace Express { interface Request { user?: AuthenticatedUser; rawBody?: Buffer; } } }
function bearer(req:Request){const v=req.headers.authorization; if(typeof v!=="string"||!v.toLowerCase().startsWith("bearer ")) return null; const t=v.slice(7).trim(); return t||null;}
export async function identityMiddleware(req:Request,res:Response,next:NextFunction){try{const token=bearer(req);if(!token)return res.status(401).json({success:false,message:"Authentication required",code:"AUTH_REQUIRED"});const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)return res.status(401).json({success:false,message:"Invalid or expired authentication token",code:"INVALID_TOKEN"});const {data:p,error:pe}=await supabase.from("users").select("id,email,username,role,status").eq("id",data.user.id).maybeSingle();if(pe)return res.status(500).json({success:false,message:"Unable to load your account",code:"PROFILE_LOOKUP_FAILED"});if(!p||p.email.toLowerCase()!==String(data.user.email||"").toLowerCase())return res.status(403).json({success:false,message:"Account profile is unavailable",code:"PROFILE_MISMATCH"});req.user=p;next();}catch(e){console.error("Identity middleware",e);res.status(500).json({success:false,message:"Authentication service error",code:"AUTH_SERVICE_ERROR"});}}
export async function authMiddleware(req:Request,res:Response,next:NextFunction){return identityMiddleware(req,res,()=>{if(!req.user)return res.status(401).json({success:false,message:"Authentication required"});if(req.user.status!=="active")return res.status(403).json({success:false,message:"Your account is not active",code:"ACCOUNT_NOT_ACTIVE",user:{id:req.user.id,username:req.user.username,status:req.user.status}});next();});}
export const requireAuth=authMiddleware;
export const requireIdentity=identityMiddleware;
export function requireAdmin(req:Request,res:Response,next:NextFunction){if(!req.user)return res.status(401).json({success:false,message:"Authentication required",code:"AUTH_REQUIRED"});if(req.user.role!=="admin")return res.status(403).json({success:false,message:"Administrator access required",code:"ADMIN_REQUIRED"});next();}
