import { Router, type Request, type Response } from "express";
import crypto from "node:crypto";
import { supabase } from "../config/supabase.js";
import { requireAuth, requireIdentity } from "../middleware/authMiddleware.js";

const router = Router();
const clean=(v:unknown,max=500)=>typeof v === "string" ? v.trim().slice(0,max) : "";
const num=(v:unknown)=>Number.isFinite(Number(v)) ? Math.max(0,Number(v)) : 0;
const activeUntil=(row:any)=>row?.status === "active" && (!row.ends_at || new Date(row.ends_at).getTime()>Date.now());
async function hasPlan(userId:string,product:string){const {data}=await supabase.from("business_subscriptions").select("status,ends_at").eq("user_id",userId).eq("product",product).maybeSingle();return activeUntil(data);}

/* Public storefront catalog. Only published products and non-sensitive shop data are exposed. */
router.get("/store/:slug",async(req,res)=>{try{const slug=clean(req.params.slug,100).toLowerCase();const {data:shop,error:shopError}=await supabase.from("business_shops").select("id,name,description,logo_url,phone,address,currency,store_slug,whatsapp_bot_id").eq("store_slug",slug).eq("is_published",true).maybeSingle();if(shopError)throw shopError;if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const {data:products,error}=await supabase.from("inventory_products").select("id,name,sku,description,image_url,selling_price,discount_percent,quantity,unit").eq("shop_id",shop.id).eq("is_published",true).order("name");if(error)throw error;return res.json({success:true,shop:{...shop,whatsapp_bot_id:undefined},products:(products??[]).map(p=>({...p,available:Number(p.quantity)>0,sale_price:Math.round(Number(p.selling_price)*(1-Math.min(Math.max(Number(p.discount_percent)||0,0),100)/100)*100)/100}))});}catch(e){console.error("Storefront",e);return res.status(500).json({success:false,message:"Unable to load storefront"});}});

/* Public order creation uses a database transaction/RPC so stock cannot be oversold by concurrent buyers. */
router.post("/store/:slug/orders",async(req,res)=>{try{const slug=clean(req.params.slug,100).toLowerCase();const {data:shop}=await supabase.from("business_shops").select("id,user_id,is_published").eq("store_slug",slug).eq("is_published",true).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const buyerName=clean(req.body?.buyerName,160),buyerPhone=clean(req.body?.buyerPhone,40),buyerEmail=clean(req.body?.buyerEmail,255),address=clean(req.body?.deliveryAddress,1000),note=clean(req.body?.deliveryNote,1000),paymentMethod=clean(req.body?.paymentMethod,30)||"cash_on_delivery";const items=Array.isArray(req.body?.items)?req.body.items.slice(0,50).map((x:any)=>({product_id:clean(x?.productId,80),quantity:Math.floor(num(x?.quantity))})).filter((x:any)=>x.product_id&&x.quantity>0):[];if(!buyerName||!buyerPhone||!items.length)return res.status(400).json({success:false,message:"Buyer name, phone and at least one product are required"});const {data,error}=await supabase.rpc("create_shop_order",{p_shop_id:shop.id,p_buyer_name:buyerName,p_buyer_phone:buyerPhone,p_buyer_email:buyerEmail||null,p_delivery_address:address||null,p_delivery_note:note||null,p_payment_method:paymentMethod,p_delivery_fee:num(req.body?.deliveryFee),p_items:items});if(error){const msg=String(error.message||"");if(msg.includes("INSUFFICIENT_STOCK"))return res.status(409).json({success:false,message:"One or more products no longer have enough stock"});if(msg.includes("SHOP_NOT_AVAILABLE"))return res.status(404).json({success:false,message:"Shop is not available"});return res.status(400).json({success:false,message:"Unable to create order"});}const order=Array.isArray(data)?data[0]:data;return res.status(201).json({success:true,order:{orderNumber:order.order_number,subtotal:Number(order.subtotal),discountAmount:Number(order.discount_amount),deliveryFee:Number(order.delivery_fee),total:Number(order.total),status:"pending",paymentStatus:"unpaid"},message:"Order received. Keep your order number to track delivery."});}catch(e){console.error("Store order",e);return res.status(500).json({success:false,message:"Unable to create order"});}});

/* Customer tracking requires two matching identifiers and never returns buyer contact details. */
router.get("/orders/track",async(req,res)=>{try{const orderNumber=clean(req.query.orderNumber,80).toUpperCase(),phone=clean(req.query.phone,40);if(!orderNumber||!phone)return res.status(400).json({success:false,message:"Order number and buyer phone are required"});const {data:o,error}=await supabase.from("shop_orders").select("id,order_number,status,payment_status,tracking_code,total,currency,created_at,updated_at,shop_id,business_shops(name,store_slug)").eq("order_number",orderNumber).eq("buyer_phone",phone).maybeSingle();if(error)throw error;if(!o)return res.status(404).json({success:false,message:"Order not found. Check the order number and phone number."});const {data:events}=await supabase.from("shop_order_events").select("status,note,created_at").eq("order_id",o.id).order("created_at",{ascending:true});const {data:items}=await supabase.from("shop_order_items").select("product_name,quantity,unit_price,line_total").eq("order_id",o.id);return res.json({success:true,order:{orderNumber:o.order_number,status:o.status,paymentStatus:o.payment_status,trackingCode:o.tracking_code,total:Number(o.total),currency:o.currency,createdAt:o.created_at,updatedAt:o.updated_at,shop:(o as any).business_shops?.name??"VSBIL Shop",items:items??[],timeline:events??[]}});}catch(e){console.error("Order tracking",e);return res.status(500).json({success:false,message:"Unable to track order"});}});

/* Shop owner administration. */
router.get("/shops/:shopId/store-settings",requireAuth,async(req,res)=>{try{const {data:shop}=await supabase.from("business_shops").select("id,name,description,logo_url,phone,address,store_slug,is_published,whatsapp_bot_id,whatsapp_auto_reply").eq("id",req.params.shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});return res.json({success:true,shop});}catch(e){return res.status(500).json({success:false,message:"Unable to load shop settings"});}});
router.patch("/shops/:shopId/store-settings",requireAuth,async(req,res)=>{try{const {data:shop}=await supabase.from("business_shops").select("id").eq("id",req.params.shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const patch:any={};for(const k of ["name","description","logo_url","phone","address"]){if(req.body?.[k]!==undefined)patch[k]=clean(req.body[k],k==="description"?2000:500)||null;}if(req.body?.storeSlug!==undefined){const slug=clean(req.body.storeSlug,80).toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-+|-+$/g,"");if(slug.length<3)return res.status(400).json({success:false,message:"Store slug must be at least 3 characters"});patch.store_slug=slug;}if(req.body?.isPublished!==undefined){const publish=Boolean(req.body.isPublished);if(publish && !(await hasPlan(req.user!.id,"inventory")))return res.status(402).json({success:false,message:"An active shop subscription is required to publish your storefront",code:"SHOP_SUBSCRIPTION_REQUIRED"});patch.is_published=publish;}if(req.body?.whatsappAutoReply!==undefined)patch.whatsapp_auto_reply=Boolean(req.body.whatsappAutoReply);const {data,error}=await supabase.from("business_shops").update(patch).eq("id",shop.id).eq("user_id",req.user!.id).select("id,name,description,logo_url,phone,address,store_slug,is_published,whatsapp_bot_id,whatsapp_auto_reply").single();if(error){if(error.code==="23505")return res.status(409).json({success:false,message:"That store URL is already in use"});throw error;}return res.json({success:true,shop:data});}catch(e){console.error("Store settings",e);return res.status(500).json({success:false,message:"Unable to update storefront"});}});
router.patch("/shops/:shopId/whatsapp",requireAuth,async(req,res)=>{try{if(!(await hasPlan(req.user!.id,"inventory"))||!(await hasPlan(req.user!.id,"whatsapp")))return res.status(402).json({success:false,message:"An active shop subscription and WhatsApp subscription are required for the integration",code:"BUNDLE_REQUIRED"});const {data:shop}=await supabase.from("business_shops").select("id").eq("id",req.params.shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const {data:bot}=await supabase.from("whatsapp_bots").select("id,status").eq("id",clean(req.body?.botId,80)).eq("user_id",req.user!.id).maybeSingle();if(!bot||bot.status!=="connected")return res.status(400).json({success:false,message:"Connect an active WhatsApp Business bot first"});const {data,error}=await supabase.from("business_shops").update({whatsapp_bot_id:bot.id,whatsapp_auto_reply:req.body?.enabled!==false}).eq("id",shop.id).eq("user_id",req.user!.id).select("id,whatsapp_bot_id,whatsapp_auto_reply").single();if(error)throw error;return res.json({success:true,shop:data});}catch(e){console.error("Shop WhatsApp link",e);return res.status(500).json({success:false,message:"Unable to connect shop to WhatsApp"});}});

router.get("/shops/:shopId/orders",requireAuth,async(req,res)=>{try{const {data:shop}=await supabase.from("business_shops").select("id").eq("id",req.params.shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const limit=Math.min(Math.max(Number(req.query.limit)||50,1),200);const {data,error}=await supabase.from("shop_orders").select("id,order_number,buyer_name,buyer_phone,buyer_email,delivery_address,subtotal,discount_amount,delivery_fee,total,payment_method,payment_status,status,tracking_code,created_at,updated_at").eq("shop_id",shop.id).order("created_at",{ascending:false}).limit(limit);if(error)throw error;return res.json({success:true,orders:data??[]});}catch(e){console.error("Shop orders",e);return res.status(500).json({success:false,message:"Unable to load shop orders"});}});
router.patch("/shops/:shopId/orders/:orderId",requireAuth,async(req,res)=>{try{const allowed=["pending","confirmed","processing","ready","shipped","delivered","cancelled","refunded"];const status=clean(req.body?.status,30);if(!allowed.includes(status))return res.status(400).json({success:false,message:"Invalid order status"});const {data:shop}=await supabase.from("business_shops").select("id").eq("id",req.params.shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Shop not found"});const patch:any={status};if(req.body?.trackingCode!==undefined)patch.tracking_code=clean(req.body.trackingCode,120)||null;const {data,error}=await supabase.from("shop_orders").update(patch).eq("id",req.params.orderId).eq("shop_id",shop.id).select("id,order_number,status,payment_status,tracking_code,total,currency,updated_at").maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,message:"Order not found"});await supabase.from("shop_order_events").insert({order_id:data.id,status,note:clean(req.body?.note,500)||null});return res.json({success:true,order:data});}catch(e){console.error("Order status",e);return res.status(500).json({success:false,message:"Unable to update order"});}});

/* Discounted shop + WhatsApp bundle. Payment is initialized by businessPayments.ts. */
router.get("/plans",(_req,res)=>res.json({success:true,plans:[{id:"inventory",name:"Shop Pro",amount:150,currency:"GHS",period:"month"},{id:"whatsapp",name:"WhatsApp Automation",amount:150,currency:"GHS",period:"month"},{id:"shop_whatsapp_bundle",name:"Shop + WhatsApp Bundle",amount:250,currency:"GHS",period:"month",savings:50}]}));

export default router;
