import { Router, type Request, type Response } from "express";
import crypto from "node:crypto";
import { supabase } from "../config/supabase.js";
import { requireAuth, requireAdmin } from "../middleware/authMiddleware.js";

const router = Router();
const JUMIA_HOSTS = new Set(["jumia.com.gh", "www.jumia.com.gh"]);
const CACHE_HOURS = 6;
const MAX_IMAGES = 5;
const FETCH_TIMEOUT_MS = 12_000;
const CRON_SECRET = process.env.CRON_SECRET?.trim() || "";

type ImportedProduct = { title:string; description:string; shortDescription:string; price:number; originalPrice:number|null; images:string[]; inStock:boolean; sourceUrl:string; currency:"GHS"; productId:string };
const clean=(value:unknown,max=5000):string=>typeof value==="string"?value.trim().slice(0,max):"";
function validJumiaUrl(value:unknown):URL|null{try{const u=new URL(String(value||"").trim());return u.protocol==="https:"&&JUMIA_HOSTS.has(u.hostname.toLowerCase())?u:null}catch{return null}}
function productIdFromUrl(url:URL):string{const p=decodeURIComponent(url.pathname);const m=p.match(/[0-9]{6,}/g);return m?.at(-1)||crypto.createHash("sha256").update(url.toString()).digest("hex").slice(0,32)}
function htmlDecode(v:string):string{return v.replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#x2F;|&#47;/gi,"/").replace(/\s+/g," ").trim()}
function meta(html:string,key:string):string{const e=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']*)["'][^>]*>`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${e}["'][^>]*>`,"i")]){const m=html.match(p);if(m?.[1])return htmlDecode(m[1])}return ""}
function elementText(html:string,hint:string):string{const m=html.match(new RegExp(`<[^>]*${hint}[^>]*>([\\s\\S]*?)<\\/[^>]+>`,"i"));return m?.[1]?htmlDecode(m[1].replace(/<[^>]+>/g," ")):""}
function money(v:string):number|null{const n=Number(v.replace(/[^0-9.,]/g,"").replace(/,/g,""));return Number.isFinite(n)&&n>=0?Math.round(n*100)/100:null}
function imageUrl(raw:string):string|null{const v=htmlDecode(raw).replace(/\\u002F/g,"/").trim();if(!v||v.startsWith("data:"))return null;try{const u=new URL(v,"https://www.jumia.com.gh");if(u.protocol!=="https:")return null;return u.toString().replace(/_300x300(?=\.[a-z0-9]+(?:\?|$))/i,"_1000x1000")}catch{return null}}
function extractImages(html:string):string[]{const out:string[]=[];const add=(v:string)=>{const u=imageUrl(v);if(u&&!out.includes(u))out.push(u)};const r=/(?:data-src|data-image|src|href)=["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=r.exec(html))&&out.length<MAX_IMAGES)if(/jumia|jcdn|image/i.test(m[1]))add(m[1]);const j=/https?:\/\/[^"'\s\\]+\.(?:jpg|jpeg|png|webp)(?:\?[^"'\s\\]+)?/gi;while((m=j.exec(html))&&out.length<MAX_IMAGES)add(m[0]);return out}
function extractPrice(html:string,original=false):number|null{const c=original?[meta(html,"product:original_price"),meta(html,"og:original_price"),elementText(html,"old-price"),elementText(html,"oldPrice"),elementText(html,"-old")]:[meta(html,"product:price:amount"),meta(html,"og:price:amount"),elementText(html,"class=[^>]*prc"),elementText(html,"data-price")];for(const x of c){const n=money(x);if(n!==null)return n}return null}
function extractStock(html:string):boolean{const t=htmlDecode(html.replace(/<[^>]+>/g," ")).toLowerCase();if(/out of stock|currently unavailable|sold out|not available/.test(t))return false;if(/in stock|available|add to cart|buy now/.test(t))return true;return true}
async function fetchProduct(sourceUrl:string):Promise<ImportedProduct>{const url=validJumiaUrl(sourceUrl);if(!url)throw new Error("Only secure Jumia Ghana product links are supported");const productId=productIdFromUrl(url);const c=new AbortController();const timer=setTimeout(()=>c.abort(),FETCH_TIMEOUT_MS);try{const r=await fetch(url.toString(),{signal:c.signal,headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"VSBIL Product Importer/1.0 (+https://vsbil.onrender.com)"}});if(r.status===401||r.status===403){const e=new Error("JUMIA_BLOCKED: Jumia is currently refusing automated server requests for this product. VSBIL will not bypass that protection.");(e as Error&{code?:string}).code="JUMIA_BLOCKED";throw e}if(!r.ok)throw new Error(`Jumia returned HTTP ${r.status}`);const html=await r.text();if(html.length<500)throw new Error("Jumia returned an incomplete product page");const title=meta(html,"og:title")||elementText(html,"<h1")||meta(html,"twitter:title");const description=meta(html,"og:description")||meta(html,"description")||elementText(html,"description");const price=extractPrice(html);const originalPrice=extractPrice(html,true);if(!title||price===null)throw new Error("Could not reliably extract the product title and price from Jumia");return{title:title.slice(0,250),description:description.slice(0,5000),shortDescription:description.slice(0,300),price,originalPrice:originalPrice&&originalPrice>price?originalPrice:null,images:extractImages(html),inStock:extractStock(html),sourceUrl:url.toString(),currency:"GHS",productId}}finally{clearTimeout(timer)}}
async function cachedProduct(sourceUrl:string):Promise<{product:ImportedProduct;stale?:boolean;requiresManual?:boolean}>{const url=validJumiaUrl(sourceUrl);if(!url)throw new Error("Only secure Jumia Ghana product links are supported");const productId=productIdFromUrl(url);const{data:cached}=await supabase.from("jumia_import_cache").select("payload,fetched_at").eq("product_id",productId).maybeSingle();if(cached?.payload&&cached.fetched_at&&Date.now()-new Date(cached.fetched_at).getTime()<CACHE_HOURS*3600000)return{product:cached.payload as ImportedProduct};try{const product=await fetchProduct(url.toString());await supabase.from("jumia_import_cache").upsert({product_id:productId,source_url:product.sourceUrl,payload:product,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"product_id"});return{product}}catch(e){if((e as Error&{code?:string}).code==="JUMIA_BLOCKED"&&cached?.payload)return{product:cached.payload as ImportedProduct,stale:true,requiresManual:true};throw e}}
function affiliateUrl(sourceUrl:string,tag?:string):string{const configured=process.env.AFFILIATE_URL?.trim();if(configured){try{const u=new URL(configured);u.searchParams.set("url",sourceUrl);if(tag)u.searchParams.set("kol_id",tag);return u.toString()}catch{}}const kol=(tag||process.env.VSBIL_JUMIA_KOL_ID)?.trim();if(!kol)return sourceUrl;const u=new URL(sourceUrl);u.searchParams.set("kol_id",kol);return u.toString()}
async function officialShopFor(adminId:string){const{data,error}=await supabase.from("business_shops").select("id,name,store_slug,is_published,affiliate_link").eq("user_id",adminId).eq("is_published",true).order("created_at",{ascending:true}).limit(10);if(error)throw error;return(data??[]).find((s:any)=>/vsbil\s*official|official\s*vsbil/i.test(String(s.name)))||(data??[])[0]||null}

router.get("/shops",requireAuth,requireAdmin,async(req,res)=>{const{data,error}=await supabase.from("business_shops").select("id,name,store_slug,is_published").eq("is_published",true).eq("user_id",req.user!.id).order("created_at",{ascending:false}).limit(100);if(error)return res.status(500).json({success:false,message:"Unable to load shops"});return res.json({success:true,shops:data??[]})});
router.post("/fetch",requireAuth,requireAdmin,async(req,res)=>{try{const sourceUrl=clean(req.body?.url,2000);if(!validJumiaUrl(sourceUrl))return res.status(400).json({success:false,message:"Paste a valid HTTPS Jumia Ghana product link"});const result=await cachedProduct(sourceUrl);return res.json({success:true,product:result.product,cachedForHours:CACHE_HOURS,stale:Boolean(result.stale),requiresManual:Boolean(result.requiresManual)})}catch(e){console.error("Jumia import fetch",e);const blocked=(e as Error&{code?:string}).code==="JUMIA_BLOCKED";return res.status(502).json({success:false,code:blocked?"JUMIA_BLOCKED":"JUMIA_FETCH_FAILED",message:e instanceof Error?e.message:"Unable to fetch Jumia product",requiresManual:blocked})}});
router.post("/publish",requireAuth,requireAdmin,async(req,res)=>{try{const sourceUrl=clean(req.body?.sourceUrl,2000);const title=clean(req.body?.title,250);const description=clean(req.body?.description,5000);const images=Array.isArray(req.body?.images)?req.body.images.filter((x:unknown):x is string=>typeof x==="string").map(imageUrl).filter((x:string|null):x is string=>Boolean(x)).slice(0,MAX_IMAGES):[];const price=Number(req.body?.price);const original=Number(req.body?.originalPrice);const affiliateTag=clean(req.body?.affiliateTag,100);if(!validJumiaUrl(sourceUrl)||!title||!Number.isFinite(price)||price<0||!images.length)return res.status(400).json({success:false,message:"Source URL, title, price and at least one valid image are required"});const requestedShop=clean(req.body?.shopId,80);const official=await officialShopFor(req.user!.id);const shopId=requestedShop||official?.id;if(!shopId)return res.status(409).json({success:false,message:"Create or publish the VSBIL Official shop before importing products"});const{data:shop}=await supabase.from("business_shops").select("id,name,affiliate_link").eq("id",shopId).eq("user_id",req.user!.id).maybeSingle();if(!shop)return res.status(404).json({success:false,message:"Selected shop was not found"});const sourceId=productIdFromUrl(new URL(sourceUrl));const affiliateLink=affiliateTag?affiliateUrl(sourceUrl,affiliateTag):(shop.affiliate_link||affiliateUrl(sourceUrl));const discount=Number.isFinite(original)&&original>price?Math.min(100,Math.max(0,Math.round((1-price/original)*10000)/100)):0;const payload={id:crypto.randomUUID(),user_id:req.user!.id,shop_id:shop.id,name:title,sku:`JUMIA-${sourceId}`.slice(0,80),description,image_url:images[0],image_urls:images,selling_price:Math.round(price*100)/100,original_price:discount?Math.round(original*100)/100:null,discount_percent:discount,quantity:0,unit:"piece",is_published:true,source:"jumia",source_url:sourceUrl,source_product_id:sourceId,source_currency:"GHS",source_in_stock:Boolean(req.body?.inStock),last_synced_at:new Date().toISOString(),affiliate_link:affiliateLink};const{data,error}=await supabase.from("inventory_products").upsert(payload,{onConflict:"shop_id,source,source_product_id"}).select().single();if(error)return res.status(400).json({success:false,message:error.message});return res.status(201).json({success:true,product:data,shop:{id:shop.id,name:shop.name},affiliateLink})}catch(e){console.error("Jumia publish",e);return res.status(500).json({success:false,message:"Unable to publish imported product"})}});
async function syncPrices(){const{data:products,error}=await supabase.from("inventory_products").select("id,source_url").eq("source","jumia").not("source_url","is",null).limit(1000);if(error)throw error;let updated=0,failed=0;for(const p of products??[]){try{const x=await fetchProduct(String(p.source_url));const{error:e}=await supabase.from("inventory_products").update({selling_price:x.price,original_price:x.originalPrice,source_in_stock:x.inStock,last_synced_at:new Date().toISOString(),image_url:x.images[0]||null,image_urls:x.images}).eq("id",p.id).eq("source","jumia");if(e)throw e;updated++}catch(e){failed++;console.error("Jumia sync failed",p.id,e)}}return{scanned:products?.length??0,updated,failed}}
router.post("/sync",requireAuth,requireAdmin,async(_req,res)=>{try{return res.json({success:true,result:await syncPrices()})}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to sync Jumia products"})}});
export const cronRouter=Router();cronRouter.post("/sync-jumia-prices",async(req:Request,res:Response)=>{if(!CRON_SECRET||req.header("x-cron-secret")!==CRON_SECRET)return res.status(401).json({success:false,message:"Unauthorized"});try{return res.json({success:true,result:await syncPrices()})}catch(e){console.error(e);return res.status(500).json({success:false,message:"Jumia price sync failed"})}});
export default router;
