import { Router,type Request,type Response } from "express";
import crypto from "node:crypto";
import { supabase } from "../config/supabase.js";
import { requireIdentity } from "../middleware/authMiddleware.js";

const router=Router(),AMOUNT=5000,GH=50;
function digest(value:string){return crypto.createHash("sha256").update(`${value}:${process.env.APP_STATE_SECRET??""}`).digest("hex")}
function securityContext(req:Request){const ip=String(req.ip??"unknown"),ua=String(req.headers["user-agent"]??"unknown");return{ipHash:digest(ip),deviceHash:digest(`${ua}|${req.headers["accept-language"]??""}`),userAgentHash:digest(ua)}}
async function securityEvent(req:Request,userId:string|null,eventType:string,severity:string,metadata:Record<string,unknown>={},amount?:number,reference?:string){const c=securityContext(req);await supabase.from("wallet_security_events").insert({user_id:userId,event_type:eventType,action:"wallet_credit",severity,amount:amount??null,currency:"GHS",requested_reference:reference??null,endpoint:req.originalUrl,ip_hash:c.ipHash,device_hash:c.deviceHash,user_agent_hash:c.userAgentHash,metadata})}

router.post("/initialize",requireIdentity,async(req:Request,res:Response)=>{try{const u=req.user!;if(u.status!=="active"&&u.status!=="pending")return res.status(403).json({success:false,message:"This account cannot make payments"});const {data:existing}=await supabase.from("payments").select("id,reference,status").eq("user_id",u.id).eq("purpose","activation").eq("status","pending").order("created_at",{ascending:false}).limit(1).maybeSingle();const reference=existing?.reference||`VSBIL-ACT-${Date.now()}-${crypto.randomBytes(6).toString("hex").toUpperCase()}`;if(!existing){const{error}=await supabase.from("payments").insert({user_id:u.id,reference,amount:AMOUNT,amount_ghs:GH,currency:"GHS",provider:"paystack",purpose:"activation",status:"pending"});if(error)return res.status(500).json({success:false,message:"Unable to create payment"})}return checkout(reference,u.email,u.id,res)}catch(e){console.error(e);return res.status(500).json({success:false,message:"Unable to initialize payment"})}});

async function checkout(reference:string,email:string,userId:string,res:Response){const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret||!process.env.APP_URL)return res.status(503).json({success:false,message:"Payment service is not configured"});const r=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/json"},body:JSON.stringify({email,amount:AMOUNT,currency:"GHS",reference,callback_url:process.env.PAYSTACK_CALLBACK_URL||`${process.env.APP_URL}/activation.html`,metadata:{user_id:userId,purpose:"activation",version:"4"}})});const d:any=await r.json().catch(()=>null);if(!r.ok||!d?.status)return res.status(502).json({success:false,message:"Unable to initialize payment"});return res.json({success:true,authorization_url:d.data.authorization_url,reference})}

async function finalize(reference:string,providerId:string,req?:Request){const{data:p}=await supabase.from("payments").select("id,user_id,reference,amount,currency,purpose,status").eq("reference",reference).eq("purpose","activation").maybeSingle();if(!p)throw new Error("PAYMENT_NOT_FOUND");if(p.status==="success"){await supabase.rpc("activate_creator_program_after_account_activation",{p_user_id:p.user_id});return{success:true,already_processed:true};}if(p.amount!==AMOUNT||p.currency!=="GHS")throw new Error("PAYMENT_AMOUNT_MISMATCH");const{data:r,error}=await supabase.rpc("activate_user_after_payment",{p_payment_id:p.id,p_provider_reference:providerId});if(error)throw error;const{error:creatorError}=await supabase.rpc("activate_creator_program_after_account_activation",{p_user_id:p.user_id});if(creatorError)throw creatorError;if(req)await securityEvent(req,p.user_id,"payment_verified","low",{provider:"paystack",provider_transaction_id:providerId,source:"server_verification"},AMOUNT/100,reference);return r}

router.get("/verify",async(req,res)=>{try{const reference=typeof req.query.reference==="string"?req.query.reference.trim():"";if(!reference)return res.status(400).json({success:false,message:"Payment reference is required"});const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret)return res.status(503).json({success:false,message:"Payment service is not configured"});const r=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret}`}});const d:any=await r.json().catch(()=>null);if(!r.ok||!d?.status||!d.data)return res.status(502).json({success:false,message:"Unable to verify payment"});const tx=d.data;if(tx.status!=="success")return res.status(400).json({success:false,message:"Payment has not been completed",status:tx.status});if(Number(tx.amount)!==AMOUNT||String(tx.currency).toUpperCase()!=="GHS")return res.status(400).json({success:false,message:"Payment amount or currency mismatch"});const{data:p}=await supabase.from("payments").select("id,user_id,reference,amount,currency,purpose").eq("reference",reference).eq("purpose","activation").maybeSingle();if(!p||tx.reference!==p.reference||tx.metadata?.user_id!==p.user_id)return res.status(400).json({success:false,message:"Payment account mismatch"});return res.json({success:true,result:await finalize(reference,String(tx.id),req)})}catch(e){console.error("Payment verify",e);return res.status(400).json({success:false,message:e instanceof Error&&e.message==="PAYMENT_NOT_FOUND"?"Payment record not found":"Unable to finalize payment"})}});

router.post("/webhook",async(req:Request,res:Response)=>{const secret=process.env.PAYSTACK_SECRET_KEY,signature=String(req.headers["x-paystack-signature"]||"");if(!secret||!signature||!req.rawBody)return res.status(401).send("Unauthorized");const expected=crypto.createHmac("sha512",secret).update(req.rawBody).digest("hex");if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return res.status(401).send("Invalid signature");try{const event=req.body;if(event?.event==="charge.success"&&event.data?.reference){const eventId=String(event.data.id||event.data.reference);const{data:seen}=await supabase.from("payment_events").select("id").eq("event_id",eventId).maybeSingle();if(!seen){const reference=String(event.data.reference),{data:p}=await supabase.from("payments").select("id,user_id,reference,amount,currency,purpose,status").eq("reference",reference).eq("purpose","activation").maybeSingle();if(!p||Number(event.data.amount)!==AMOUNT||String(event.data.currency).toUpperCase()!=="GHS"||event.data.metadata?.user_id!==p.user_id){if(p)await securityEvent(req,p.user_id,"forged_or_mismatched_payment_callback","critical",{event_id:eventId,payload:event.data},Number(event.data.amount??0)/100,reference);return res.status(400).send("Payment mismatch")}await supabase.from("payment_events").insert({event_id:eventId,reference,event_name:String(event.event),payload:event.data});await finalize(reference,eventId,req)}}return res.sendStatus(200)}catch(e){console.error("Paystack webhook",e);return res.sendStatus(500)}});

router.post("/wallet-credit",requireIdentity,async(req:Request,res:Response)=>{const userId=req.user!.id;const amount=Number(req.body?.amount);const reference=String(req.body?.reference??"").trim();await securityEvent(req,userId,"unauthorized_wallet_credit_attempt","critical",{client_supplied_balance:req.body?.balance??null,client_supplied_new_balance:req.body?.newBalance??null,reason:"browser_client_cannot_mint_wallet_credit"},Number.isFinite(amount)?amount:undefined,reference);return res.status(403).json({success:false,code:"WALLET_CREDIT_SERVER_ONLY",message:"Wallet credits can only be created from a verified payment transaction."})});

export default router;
