import { Router } from "express";
import crypto from "node:crypto";
import { requireIdentity } from "../middleware/authMiddleware.js";
import { supabase } from "../config/supabase.js";

const router=Router();
const ref=()=>`VSBIL-SHOP-${Date.now()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;

router.get('/plans',(_req,res)=>res.json({success:true,plans:[{id:'free',amount:0,setup:0,products:20,conversations:100,feePercent:5},{id:'pro',amount:149,setup:100,products:1000,conversations:1000,extraConversation:0.5,feePercent:3,currency:'GHS',period:'month'}]}));

router.post('/subscribe',requireIdentity,async(req,res)=>{try{const plan=String(req.body?.plan||'').toLowerCase();if(plan==='free'){const end=new Date(Date.now()+3650*86400000).toISOString();const {data,error}=await supabase.from('business_subscriptions').upsert({user_id:req.user!.id,product:'shop',plan:'free',status:'active',starts_at:new Date().toISOString(),ends_at:end},{onConflict:'user_id,product'}).select().single();if(error)throw error;await supabase.from('business_shops').update({is_pro:false,pro_expires_at:null}).eq('user_id',req.user!.id);return res.json({success:true,subscription:data});}if(plan!=='pro')return res.status(400).json({success:false,message:'Choose Free or Pro'});const {data:existing}=await supabase.from('business_subscriptions').select('plan,status,ends_at').eq('user_id',req.user!.id).eq('product','shop').maybeSingle();const first=!(existing?.plan==='pro'&&existing.status==='active'&&existing.ends_at&&new Date(existing.ends_at).getTime()>Date.now());const amount=first?249:149;const reference=ref();const {error}=await supabase.from('business_subscription_payments').insert({id:crypto.randomUUID(),user_id:req.user!.id,purpose:first?'shop_pro_first':'shop_pro_renewal',amount,currency:'GHS',reference,status:'pending'});if(error)throw error;const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret||!process.env.APP_URL)return res.status(503).json({success:false,message:'Payment service is not configured'});const pay=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},body:JSON.stringify({email:req.user!.email,amount:amount*100,currency:'GHS',reference,callback_url:`${process.env.APP_URL}/business.html?shop_payment=${encodeURIComponent(reference)}`,metadata:{type:'shop_subscription',user_id:req.user!.id,plan:'pro',first}})});const data:any=await pay.json().catch(()=>null);if(!pay.ok||!data?.status)return res.status(502).json({success:false,message:'Unable to initialize Shop Pro payment'});return res.json({success:true,authorization_url:data.data.authorization_url,reference,amount,setupFee:first?100:0});}catch(e){console.error('Shop subscription init',e);return res.status(500).json({success:false,message:'Unable to start Shop subscription'});}});

router.get('/verify',requireIdentity,async(req,res)=>{try{const reference=String(req.query.reference||'').trim(),secret=process.env.PAYSTACK_SECRET_KEY;if(!reference||!secret)return res.status(400).json({success:false,message:'Payment reference is required'});const pay=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret}`}});const data:any=await pay.json().catch(()=>null);if(!pay.ok||!data?.status||data.data?.status!=='success')return res.status(400).json({success:false,message:'Payment has not been verified'});const tx=data.data;const {data:p}=await supabase.from('business_subscription_payments').select('*').eq('reference',reference).eq('user_id',req.user!.id).maybeSingle();if(!p||Number(tx.amount)!==Math.round(Number(p.amount)*100)||String(tx.currency).toUpperCase()!=='GHS'||tx.metadata?.user_id!==req.user!.id)return res.status(400).json({success:false,message:'Payment mismatch'});if(p.status==='paid'){return res.json({success:true,alreadyProcessed:true});}const end=new Date(Date.now()+30*86400000).toISOString();const {error:paymentError}=await supabase.from('business_subscription_payments').update({status:'paid',provider_transaction_id:String(tx.id),paid_at:new Date().toISOString()}).eq('id',p.id).eq('status','pending');if(paymentError)throw paymentError;const {data:sub,error}=await supabase.from('business_subscriptions').upsert({user_id:req.user!.id,product:'shop',plan:'pro',status:'active',starts_at:new Date().toISOString(),ends_at:end},{onConflict:'user_id,product'}).select().single();if(error)throw error;await supabase.from('business_shops').update({is_pro:true,pro_expires_at:end}).eq('user_id',req.user!.id);return res.json({success:true,subscription:sub});}catch(e){console.error('Shop subscription verify',e);return res.status(500).json({success:false,message:'Unable to verify Shop payment'});}});

export default router;
