-- VSBIL PRODUCTION UPGRADE v3
-- Run after src/db/schema.sql in Supabase SQL Editor. Review in staging first.
create table if not exists public.payment_events(id uuid primary key default gen_random_uuid(),event_id text not null unique,reference text not null,event_name text not null,payload jsonb not null,created_at timestamptz not null default now());
create table if not exists public.system_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
create table if not exists public.announcements(id uuid primary key default gen_random_uuid(),title text not null,message text not null,active boolean not null default true,created_by uuid references public.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.user_preferences(user_id uuid primary key references public.users(id) on delete cascade,campaign_notifications boolean not null default true,activity_notifications boolean not null default true,updated_at timestamptz not null default now());
insert into public.system_settings(key,value) values ('withdrawal_limits','{"min_ghs":10,"max_ghs":5000}'::jsonb),('activation','{"amount_ghs":50,"launch":true}'::jsonb) on conflict(key) do nothing;
create or replace function public.ensure_preferences() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into user_preferences(user_id) values(new.id) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists users_preferences_trigger on public.users;create trigger users_preferences_trigger after insert on public.users for each row execute function public.ensure_preferences();
insert into public.user_preferences(user_id) select id from public.users on conflict(user_id) do nothing;
create or replace function public.request_withdrawal(p_user_id uuid,p_amount bigint,p_method text,p_account_details jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare b bigint; w uuid; after_balance bigint; existing_count integer; begin if p_amount<1000 then raise exception 'MINIMUM_WITHDRAWAL'; end if; if p_method not in ('mobile_money','bank') then raise exception 'INVALID_METHOD'; end if; select count(*) into existing_count from withdrawals where user_id=p_user_id and status in ('pending','approved'); if existing_count>0 then raise exception 'PENDING_WITHDRAWAL'; end if; select available into b from wallets where user_id=p_user_id for update; if b is null or b<p_amount then raise exception 'INSUFFICIENT_BALANCE'; end if; update wallets set available=available-p_amount,pending=pending+p_amount,updated_at=now() where user_id=p_user_id returning available into after_balance; insert into withdrawals(user_id,amount,method,account_details,status) values(p_user_id,p_amount,p_method,p_account_details,'pending') returning id into w; insert into wallet_ledger(user_id,entry_type,amount,balance_after,reference_id,description) values(p_user_id,'withdrawal',-p_amount,after_balance,w,'Withdrawal requested'); insert into notifications(user_id,title,message) values(p_user_id,'Withdrawal submitted','Your withdrawal request is awaiting review.'); return jsonb_build_object('id',w,'amount',p_amount/100.0,'status','pending'); end; $$;
create or replace function public.review_withdrawal(p_withdrawal_id uuid,p_status text,p_admin_id uuid,p_note text) returns jsonb language plpgsql security definer set search_path=public as $$ declare w withdrawals%rowtype; after_balance bigint; begin if p_status not in ('approved','rejected','paid') then raise exception 'INVALID_STATUS';end if;select * into w from withdrawals where id=p_withdrawal_id for update;if not found then raise exception 'WITHDRAWAL_NOT_FOUND';end if;if w.status in ('paid','rejected') then raise exception 'WITHDRAWAL_FINALIZED';end if;if p_status='rejected' then update wallets set pending=greatest(0,pending-w.amount),available=available+w.amount,updated_at=now() where user_id=w.user_id returning available into after_balance;insert into wallet_ledger(user_id,entry_type,amount,balance_after,reference_id,description) values(w.user_id,'refund',w.amount,after_balance,w.id,'Rejected withdrawal refunded');elsif p_status='paid' then update wallets set pending=greatest(0,pending-w.amount),lifetime_withdrawn=lifetime_withdrawn+w.amount,updated_at=now() where user_id=w.user_id;update platform_wallet set balance=greatest(0,balance-w.amount),updated_at=now() where id=1;end if;update withdrawals set status=p_status,admin_note=nullif(p_note,''),processed_at=case when p_status in ('paid','rejected') then now() else processed_at end where id=w.id;insert into audit_logs(admin_id,action,entity_type,entity_id,metadata) values(p_admin_id,'withdrawal_'||p_status,'withdrawal',w.id,jsonb_build_object('amount',w.amount,'note',p_note));insert into notifications(user_id,title,message) values(w.user_id,case when p_status='paid' then 'Withdrawal paid' when p_status='rejected' then 'Withdrawal rejected' else 'Withdrawal approved' end,case when p_status='paid' then 'Your withdrawal has been marked as paid.' when p_status='rejected' then coalesce(p_note,'Your withdrawal was rejected and the funds were returned.') else 'Your withdrawal passed admin review and is ready for payout.' end);return jsonb_build_object('id',w.id,'status',p_status);end; $$;
-- Protect ledger integrity and enable RLS for upgrade tables.
alter table public.payment_events enable row level security;alter table public.system_settings enable row level security;alter table public.announcements enable row level security;alter table public.user_preferences enable row level security;
