-- VSBIL BUSINESS SUITE V1
create extension if not exists pgcrypto;
create table if not exists business_shops(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,name text not null,phone text,address text,currency text not null default 'GHS',created_at timestamptz not null default now());
create table if not exists inventory_products(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,shop_id uuid not null references business_shops(id) on delete cascade,name text not null,sku text not null,quantity integer not null default 0 check(quantity>=0),selling_price numeric(14,2) not null default 0 check(selling_price>=0),cost_price numeric(14,2) not null default 0 check(cost_price>=0),reorder_level integer not null default 0 check(reorder_level>=0),unit text not null default 'piece',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(shop_id,sku));
create table if not exists inventory_stock_movements(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,product_id uuid not null references inventory_products(id) on delete cascade,change integer not null,reason text,created_at timestamptz not null default now());
create table if not exists business_invoices(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,invoice_number text not null,client_name text not null,client_email text,client_phone text,items jsonb not null default '[]',subtotal numeric(14,2) not null default 0,tax numeric(14,2) not null default 0,discount numeric(14,2) not null default 0,total numeric(14,2) not null default 0,status text not null default 'draft' check(status in ('draft','sent','paid','overdue','cancelled')),due_date date,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,invoice_number));
create table if not exists landlord_properties(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,name text not null,address text,rent_amount numeric(14,2) not null default 0,rent_cycle text not null default 'monthly' check(rent_cycle in ('monthly','quarterly','yearly')),notes text,created_at timestamptz not null default now());
create table if not exists landlord_tenants(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,property_id uuid not null references landlord_properties(id) on delete cascade,name text not null,phone text,email text,unit text,rent_amount numeric(14,2) not null default 0,due_day integer not null default 1 check(due_day between 1 and 31),utility_amount numeric(14,2) not null default 0,status text not null default 'active' check(status in ('active','inactive')),created_at timestamptz not null default now());
create table if not exists landlord_payments(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,tenant_id uuid not null references landlord_tenants(id) on delete cascade,amount numeric(14,2) not null check(amount>0),payment_type text not null default 'rent',paid_at timestamptz not null default now(),reference text,notes text,created_at timestamptz not null default now());
create table if not exists church_offerings(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,church_name text not null,offering_date date not null,entries jsonb not null default '[]',total_amount numeric(14,2) not null default 0,notes text,created_at timestamptz not null default now());
create table if not exists funeral_campaigns(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,title text not null,slug text not null unique,story text,target_amount numeric(14,2) not null default 0,amount_raised numeric(14,2) not null default 0,currency text not null default 'GHS',beneficiary_name text,beneficiary_phone text,status text not null default 'active' check(status in ('draft','active','paused','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists funeral_contributions(id uuid primary key,campaign_id uuid not null references funeral_campaigns(id) on delete cascade,donor_name text not null,donor_phone text,amount numeric(14,2) not null check(amount>0),status text not null default 'pending' check(status in ('pending','paid','failed','refunded')),reference text not null unique,anonymous boolean not null default false,created_at timestamptz not null default now());
create table if not exists business_subscription_payments(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,purpose text not null,amount numeric(14,2) not null,currency text not null default 'GHS',reference text not null unique,status text not null default 'pending',provider_transaction_id text,created_at timestamptz not null default now(),paid_at timestamptz);
create table if not exists business_subscriptions(id uuid primary key,user_id uuid not null references public.users(id) on delete cascade,product text not null,plan text not null,status text not null default 'active' check(status in ('active','expired','cancelled')),starts_at timestamptz not null default now(),ends_at timestamptz not null,created_at timestamptz not null default now(),unique(user_id,product));
create index if not exists inventory_products_user_idx on inventory_products(user_id);create index if not exists invoices_user_idx on business_invoices(user_id,created_at desc);create index if not exists tenants_user_idx on landlord_tenants(user_id);create index if not exists offerings_user_idx on church_offerings(user_id,offering_date desc);create index if not exists funeral_user_idx on funeral_campaigns(user_id,created_at desc);create index if not exists funeral_contribution_idx on funeral_contributions(campaign_id,created_at desc);
alter table business_shops enable row level security;alter table inventory_products enable row level security;alter table inventory_stock_movements enable row level security;alter table business_invoices enable row level security;alter table landlord_properties enable row level security;alter table landlord_tenants enable row level security;alter table landlord_payments enable row level security;alter table church_offerings enable row level security;alter table funeral_campaigns enable row level security;alter table funeral_contributions enable row level security;alter table business_subscription_payments enable row level security;alter table business_subscriptions enable row level security;
create or replace function public.increment_funeral_raised(p_campaign_id uuid,p_amount numeric,p_fee numeric default 0) returns void language plpgsql security definer set search_path=public as $$ begin update funeral_campaigns set amount_raised=amount_raised+greatest(p_amount,0),updated_at=now() where id=p_campaign_id; end $$;
revoke all on function public.increment_funeral_raised(uuid,numeric,numeric) from public; grant execute on function public.increment_funeral_raised(uuid,numeric,numeric) to service_role;
