-- VSBIL SOCIAL / TRUST / DISCOVERY / SUPPORT V2
-- Independent social and trust layer. Existing YouTube, activation and business modules remain separate.
create extension if not exists pgcrypto;

alter table public.users add column if not exists account_visibility text not null default 'public' check(account_visibility in ('public','private'));
alter table public.users add column if not exists discoverable boolean not null default true;
alter table public.users add column if not exists allow_direct_messages text not null default 'followers' check(allow_direct_messages in ('everyone','followers','nobody'));
alter table public.users add column if not exists content_participant boolean not null default false;
alter table public.users add column if not exists moderation_status text not null default 'clear' check(moderation_status in ('clear','review','restricted','banned'));
alter table public.users add column if not exists shop_verified boolean not null default false;
alter table public.users add column if not exists shop_verification_level text not null default 'none' check(shop_verification_level in ('none','basic','verified','trusted'));

create table if not exists public.social_settings(user_id uuid primary key references public.users(id) on delete cascade,show_activity boolean not null default true,allow_tagging boolean not null default true,allow_comments boolean not null default true,show_followers boolean not null default true,discover_posts boolean not null default true,theme text not null default 'system' check(theme in ('system','light','dark')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.follows(follower_id uuid not null references public.users(id) on delete cascade,following_id uuid not null references public.users(id) on delete cascade,status text not null default 'accepted' check(status in ('pending','accepted')),created_at timestamptz not null default now(),primary key(follower_id,following_id),check(follower_id<>following_id));
create index if not exists follows_following_idx on public.follows(following_id,created_at desc);

create table if not exists public.social_posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,body text not null default '',media_url text,media_type text check(media_type in ('image','video','audio','link')),visibility text not null default 'public' check(visibility in ('public','followers','private')),originality_status text not null default 'pending' check(originality_status in ('pending','approved','review','rejected')),moderation_status text not null default 'pending' check(moderation_status in ('pending','approved','review','rejected','removed')),quality_score numeric(5,2) not null default 0,engagement_score numeric(12,4) not null default 0,allow_comments boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists social_posts_feed_idx on public.social_posts(created_at desc,moderation_status,visibility);
create index if not exists social_posts_user_idx on public.social_posts(user_id,created_at desc);
create table if not exists public.social_post_likes(post_id uuid not null references public.social_posts(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,created_at timestamptz not null default now(),primary key(post_id,user_id));
create table if not exists public.social_comments(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.social_posts(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,body text not null,moderation_status text not null default 'approved' check(moderation_status in ('approved','review','removed')),created_at timestamptz not null default now());

create table if not exists public.shop_reviews(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.business_shops(id) on delete cascade,order_id uuid references public.shop_orders(id) on delete set null,buyer_id uuid references public.users(id) on delete set null,rating smallint not null check(rating between 1 and 5),title text,body text not null default '',verified_purchase boolean not null default false,status text not null default 'published' check(status in ('published','hidden','review')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists shop_reviews_buyer_order_uidx on public.shop_reviews(buyer_id,order_id) where buyer_id is not null and order_id is not null;
create index if not exists shop_reviews_shop_idx on public.shop_reviews(shop_id,status,created_at desc);

create table if not exists public.support_complaints(id uuid primary key default gen_random_uuid(),reporter_id uuid references public.users(id) on delete set null,target_user_id uuid references public.users(id) on delete set null,shop_id uuid references public.business_shops(id) on delete set null,order_id uuid references public.shop_orders(id) on delete set null,post_id uuid references public.social_posts(id) on delete set null,category text not null check(category in ('fake_shop','counterfeit','fraud','item_not_received','item_not_as_described','abuse','spam','copyright','sexual_content','privacy','payment','other')),subject text not null,description text not null,attachments jsonb not null default '[]'::jsonb,status text not null default 'open' check(status in ('open','investigating','resolved','rejected','escalated')),priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),resolution text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists complaints_status_idx on public.support_complaints(status,priority,created_at desc);
create table if not exists public.support_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_complaints(id) on delete cascade,sender_id uuid references public.users(id) on delete set null,body text not null,internal boolean not null default false,created_at timestamptz not null default now());

create table if not exists public.shop_verification_requests(id uuid primary key default gen_random_uuid(),shop_id uuid not null references public.business_shops(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,documents jsonb not null default '[]'::jsonb,business_name text,ghana_card_last4 text,notes text,status text not null default 'pending' check(status in ('pending','approved','rejected','more_info')),reviewed_by uuid references public.users(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now());
create index if not exists shop_verification_status_idx on public.shop_verification_requests(status,created_at desc);

create table if not exists public.direct_messages(id uuid primary key default gen_random_uuid(),sender_id uuid not null references public.users(id) on delete cascade,recipient_id uuid not null references public.users(id) on delete cascade,body text not null,moderation_status text not null default 'approved' check(moderation_status in ('approved','review','blocked')),read_at timestamptz,created_at timestamptz not null default now(),check(sender_id<>recipient_id));
create index if not exists direct_messages_recipient_idx on public.direct_messages(recipient_id,created_at desc);

create table if not exists public.promotion_campaigns(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.users(id) on delete cascade,shop_id uuid references public.business_shops(id) on delete set null,post_id uuid references public.social_posts(id) on delete set null,budget numeric(14,2) not null check(budget>0),daily_limit numeric(14,2),target jsonb not null default '{}'::jsonb,status text not null default 'draft' check(status in ('draft','pending','active','paused','completed','rejected')),impressions bigint not null default 0,clicks bigint not null default 0,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now());
create index if not exists promotions_owner_idx on public.promotion_campaigns(owner_id,status,created_at desc);

create table if not exists public.moderation_cases(id uuid primary key default gen_random_uuid(),post_id uuid references public.social_posts(id) on delete cascade,user_id uuid references public.users(id) on delete cascade,case_type text not null check(case_type in ('nudity','copyright','violence','spam','fraud','quality','other')),confidence numeric(5,4),provider text,reason text,action text not null default 'review' check(action in ('allow','review','remove','restrict','ban')),evidence jsonb not null default '{}'::jsonb,reviewed_by uuid references public.users(id) on delete set null,created_at timestamptz not null default now());
create index if not exists moderation_cases_queue_idx on public.moderation_cases(action,created_at desc);

create table if not exists public.audit_events(id uuid primary key default gen_random_uuid(),actor_id uuid references public.users(id) on delete set null,target_user_id uuid references public.users(id) on delete set null,event_type text not null,metadata jsonb not null default '{}'::jsonb,ip_hash text,user_agent_hash text,created_at timestamptz not null default now());
create index if not exists audit_events_target_idx on public.audit_events(target_user_id,created_at desc);

alter table public.social_settings enable row level security;alter table public.follows enable row level security;alter table public.social_posts enable row level security;alter table public.social_post_likes enable row level security;alter table public.social_comments enable row level security;alter table public.shop_reviews enable row level security;alter table public.support_complaints enable row level security;alter table public.support_messages enable row level security;alter table public.shop_verification_requests enable row level security;alter table public.direct_messages enable row level security;alter table public.promotion_campaigns enable row level security;alter table public.moderation_cases enable row level security;alter table public.audit_events enable row level security;

create or replace function public.social_touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
drop trigger if exists social_settings_touch on public.social_settings;create trigger social_settings_touch before update on public.social_settings for each row execute function public.social_touch_updated_at();
drop trigger if exists social_posts_touch on public.social_posts;create trigger social_posts_touch before update on public.social_posts for each row execute function public.social_touch_updated_at();
drop trigger if exists complaints_touch on public.support_complaints;create trigger complaints_touch before update on public.support_complaints for each row execute function public.social_touch_updated_at();
drop trigger if exists shop_reviews_touch on public.shop_reviews;create trigger shop_reviews_touch before update on public.shop_reviews for each row execute function public.social_touch_updated_at();

create or replace function public.social_follow_counts(p_user uuid) returns jsonb language sql stable as $$select jsonb_build_object('followers',(select count(*) from public.follows where following_id=p_user and status='accepted'),'following',(select count(*) from public.follows where follower_id=p_user and status='accepted'))$$;

-- Admin/service role remains responsible for moderation, verification and audit writes. Client RLS is intentionally restrictive.
