import express from "express";
import cors from "cors";
import helmet from "helmet";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import authRouter from "./routes/auth.js";
import authAdvancedRouter from "./routes/authAdvanced.js";
import authProductionRouter from "./routes/authProduction.js";
import authProductionPatchRouter from "./routes/authProductionPatch.js";
import oauthRouter from "./routes/oauth.js";
import paymentRouter from "./routes/payment.js";
import dashboardRouter from "./routes/dashboard.js";
import withdrawalRouter from "./routes/withdrawals.js";
import adminRouter from "./routes/admin.js";
import adminControlRouter from "./routes/adminControl.js";
import supportAdminRouter from "./routes/supportAdmin.js";
import campaignAdminRouter from "./routes/campaignAdmin.js";
import activityRouter from "./routes/activities.js";
import usersRouter from "./routes/users.js";
import notificationRouter from "./routes/notifications.js";
import youtubeRouter from "./routes/youtube.js";
import whatsappRouter from "./routes/whatsapp.js";
import businessRouter from "./routes/business.js";
import businessPaymentsRouter from "./routes/businessPayments.js";
import businessCommerceRouter from "./routes/businessCommerce.js";
import businessAffiliateRouter from "./routes/businessAffiliate.js";
import storefrontEnrichmentRouter from "./routes/storefrontEnrichment.js";
import verificationRouter from "./routes/verification.js";
import supportRouter from "./routes/support.js";
import socialRouter from "./routes/social.js";
import socialMonetizationRouter from "./routes/socialMonetization.js";
import creatorProgramRouter from "./routes/creatorProgram.js";
import jumiaImporterRouter,{cronRouter as jumiaCronRouter} from "./routes/jumiaImporter.js";
import marketplaceRouter from "./routes/marketplace.js";
import { rateLimit } from "./middleware/rateLimit.js";
import { featureEnabled, featureGate } from "./middleware/featureGate.js";

const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const app=express();
const nodeEnv=process.env.NODE_ENV?.trim().toLowerCase()||"development";
const isProduction=nodeEnv==="production";
const normalizeOrigin=(value:string)=>value.trim().replace(/\/+$/g,"").toLowerCase();
const configuredOrigins=new Set((process.env.APP_URL??"").split(",").map(normalizeOrigin).filter(Boolean));
const productionOrigins=new Set(["https://vsbil.onrender.com",...configuredOrigins]);
app.disable("x-powered-by");app.set("trust proxy",1);
app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:"cross-origin"},referrerPolicy:{policy:"strict-origin-when-cross-origin"},frameguard:{action:"sameorigin"},hsts:isProduction?undefined:false}));
app.use(cors({origin:(origin,cb)=>{if(!origin)return cb(null,true);const normalized=normalizeOrigin(origin);if(!isProduction)return cb(null,true);return productionOrigins.has(normalized)?cb(null,true):cb(new Error("CORS origin denied"));},credentials:true,methods:["GET","POST","PUT","PATCH","DELETE","OPTIONS"],allowedHeaders:["Content-Type","Authorization","Accept","X-Requested-With","X-Idempotency-Key","X-Cron-Secret"],exposedHeaders:["X-Request-Id"],optionsSuccessStatus:204}));
app.use(express.json({limit:"8mb",verify:(req,_res,buf)=>{(req as express.Request&{rawBody?:Buffer}).rawBody=Buffer.from(buf)}}));
app.use((req,res,next)=>{res.setHeader("X-Request-Id",`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`);if(req.path.startsWith("/api/")){res.setHeader("Cache-Control","no-store");res.setHeader("Pragma","no-cache")}next()});

// Safe public read-only feature state. Mutation remains admin-only.
app.get("/api/features",async(_req,res)=>{const keys=["creator_program","business_suite","landlord","services","church","funeral","activities","marketplace","youtube","whatsapp","social","social_monetization","jumia_import","support","verification"];const entries=await Promise.all(keys.map(async key=>[key,await featureEnabled(key)] as const));res.setHeader("Cache-Control","no-store");res.json({success:true,features:Object.fromEntries(entries)});});

app.use("/api/auth/production",rateLimit({windowMs:60000,max:15,key:req=>`${req.ip}:production-auth`}),authProductionRouter);
app.use("/api/auth/production",authProductionPatchRouter);
app.use("/api/auth",rateLimit({windowMs:60000,max:30,key:req=>`${req.ip}:auth`}),authRouter);
app.use("/api/auth/advanced",rateLimit({windowMs:60000,max:12,key:req=>`${req.ip}:advanced-auth`}),authAdvancedRouter);
app.use("/api/auth",rateLimit({windowMs:60000,max:20,key:req=>`${req.ip}:oauth`}),oauthRouter);
app.use("/api/payment",rateLimit({windowMs:60000,max:20,key:req=>`${req.ip}:payment`}),paymentRouter);
app.use("/api/youtube",rateLimit({windowMs:60000,max:20,key:req=>`${req.ip}:youtube`}),featureGate("youtube"),youtubeRouter);
app.use("/api/whatsapp",featureGate("whatsapp"),whatsappRouter);
app.use("/api/marketplace",rateLimit({windowMs:60000,max:80,key:req=>`${req.ip}:marketplace`}),featureGate("marketplace"),marketplaceRouter);
app.use("/api/business-commerce",rateLimit({windowMs:60000,max:80,key:req=>`${req.ip}:commerce`}),featureGate("business_suite"),storefrontEnrichmentRouter);
app.use("/api/business-commerce",rateLimit({windowMs:60000,max:80,key:req=>`${req.ip}:commerce`}),featureGate("business_suite"),businessCommerceRouter);
app.use("/api/business",rateLimit({windowMs:60000,max:100,key:req=>`${req.ip}:business`}),featureGate("business_suite"),businessRouter);
app.use("/api/business-payments",rateLimit({windowMs:60000,max:20,key:req=>`${req.ip}:business-payments`}),featureGate("business_suite"),businessPaymentsRouter);
app.use("/api/business-affiliate",rateLimit({windowMs:60000,max:30,key:req=>`${req.ip}:business-affiliate`}),featureGate("business_suite"),businessAffiliateRouter);
app.use("/api/verification",rateLimit({windowMs:60000,max:10,key:req=>`${req.ip}:verification`}),featureGate("verification"),verificationRouter);
app.use("/api/support",rateLimit({windowMs:60000,max:12,key:req=>`${req.ip}:support`}),featureGate("support"),supportRouter);
app.use("/api/social",rateLimit({windowMs:60000,max:100,key:req=>`${req.ip}:social`}),featureGate("social"),socialRouter);
app.use("/api/social-monetization",rateLimit({windowMs:60000,max:80,key:req=>`${req.ip}:social-monetization`}),featureGate("social_monetization"),socialMonetizationRouter);
app.use("/api/creator-program",rateLimit({windowMs:60000,max:20,key:req=>`${req.ip}:creator-program`}),featureGate("creator_program"),creatorProgramRouter);
app.use("/api/import/jumia",rateLimit({windowMs:60000,max:10,key:req=>`${req.ip}:jumia-import`}),featureGate("jumia_import"),jumiaImporterRouter);
app.use("/api/cron",jumiaCronRouter);
app.use("/api/dashboard",dashboardRouter);app.use("/api/withdrawals",withdrawalRouter);
app.use("/api/activities",rateLimit({windowMs:60000,max:60,key:req=>`${req.ip}:activities`}),featureGate("activities"),activityRouter);
app.use("/api/users",usersRouter);app.use("/api/notifications",notificationRouter);
app.use("/api/admin",supportAdminRouter);app.use("/api/admin",campaignAdminRouter);app.use("/api/admin",adminRouter);app.use("/api/admin",adminControlRouter);
app.get("/api/health",(_req,res)=>res.json({success:true,service:"VSBIL API",status:"online",environment:nodeEnv,time:new Date().toISOString()}));

const publicDirectory=path.resolve(__dirname,"../public");
const shellVersion="20260902-1";
const inject=(html:string)=>{const shell=`\n<link rel="manifest" href="/manifest.webmanifest?v=${shellVersion}"><link rel="icon" href="/assets/vsbil-logo.svg" type="image/svg+xml"><meta name="theme-color" content="#070a12"><link rel="stylesheet" href="/css/brand.css?v=${shellVersion}"><link rel="stylesheet" href="/css/site-shell.css?v=${shellVersion}"><link rel="stylesheet" href="/css/theme-fixes.css?v=${shellVersion}"><link rel="stylesheet" href="/css/social.css?v=${shellVersion}"><script src="/js/site-shell.js?v=${shellVersion}" defer></script>`;const withHead=html.replace("</head>",`${html.includes("/js/site-shell.js")?"":shell}</head>`);return withHead.replace("</body>",`${html.includes("/js/pwa.js")?"":`<script src="/js/pwa.js?v=${shellVersion}" defer></script>`}</body>`)};
const send=async(file:string,res:express.Response,next:express.NextFunction)=>{try{const html=await readFile(file,"utf8");return res.status(200).type("html").setHeader("X-Content-Type-Options","nosniff").setHeader("Cache-Control","no-store").send(inject(html))}catch(error:any){if(error?.code==="ENOENT")return next();return next(error)}};

const pageFeatureByPath: Record<string,string> = { "/landlord.html":"landlord", "/services.html":"services", "/church.html":"church", "/funeral.html":"funeral" };
app.get(/^\/.*\.html$/,(req,res,next)=>{const feature=pageFeatureByPath[req.path.toLowerCase()];if(!feature)return next();featureEnabled(feature).then(enabled=>enabled?send(path.join(publicDirectory,req.path.replace(/^\/+/,"")),res,next):res.status(403).type("html").send("<h1>Feature unavailable</h1><p>This feature is currently unavailable.</p>")).catch(next)});
app.get("/",(_req,res,next)=>send(path.join(publicDirectory,"index.html"),res,next));
app.get("/admin/import/jumia",(_req,res,next)=>send(path.join(publicDirectory,"admin","import","jumia.html"),res,next));
app.get(/^\/.*\.html$/,(req,res,next)=>{const relative=req.path.replace(/^\/+/,"");const safe=path.normalize(relative);if(safe.startsWith("..")||path.isAbsolute(safe))return res.status(400).end();return send(path.join(publicDirectory,safe),res,next)});
app.use(express.static(publicDirectory,{extensions:["html"],setHeaders:res=>res.setHeader("X-Content-Type-Options","nosniff")}));
app.all("/api/*splat",(_req,res)=>res.status(404).json({success:false,message:"API endpoint not found",code:"NOT_FOUND"}));
app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error("Unhandled application error",error);if(res.headersSent)return;const corsError=error instanceof Error&&error.message==="CORS origin denied";res.status(corsError?403:500).json({success:false,message:corsError?"Origin is not allowed":"Internal server error",code:corsError?"CORS_DENIED":"INTERNAL_ERROR",requestId:res.getHeader("X-Request-Id")})});
export default app;
